services:
  postgres:
    image: postgres:16.6
    container_name: life-metrics-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: life-metrics-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq-init.sh:/usr/local/bin/rabbitmq-init.sh
    command: >
      bash -c "
        chmod +x /usr/local/bin/rabbitmq-init.sh &&
        /usr/local/bin/rabbitmq-init.sh
      "
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "rabbitmqctl status && rabbitmqctl list_users | grep ${RABBITMQ_USER}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  postgres_data:
  rabbitmq_data:
